### ISSUE TITLE
[BUG] fetch_data(): Not all rnames found or unique  

### ISSUE THREAD

**Issue by dimalvovs** [LieberInstitute/spatialLIBD#87] opened 2024-10-08 20:50 UTC
## Describe the bug

Thank you for your work! I wanted to report that no data object is returned with `fetch_data(type='spe').

### Provide a minimally reproducible example (reprex)

```
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("spatialLIBD")

library(spatialLIBD)

spe <- fetch_data(type = "spe")
```
results in 

```
snapshotDate(): 2024-04-29
adding rname 'https://www.dropbox.com/s/f4wcvtdq428y73p/Human_DLPFC_Visium_processedData_sce_scran_spatialLIBD.Rdata?dl=1'
  |======================================================================| 100%
  |======================================================================| 100%

Error in BiocFileCache::bfcrpath(bfc, url) : 
  not all 'rnames' found or unique.
In addition: Warning message:
In value[[3L]](cond) : 
trying to add rname 'https://www.dropbox.com/s/f4wcvtdq428y73p/Human_DLPFC_Visium_processedData_sce_scran_spatialLIBD.Rdata?dl=1' produced error:
  HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)
> str(spe)
Error: object 'spe' not found
```
## Expected behavior

spe object is created.

## R Session Information

```R
options(width = 120)
> sessionInfo()
R version 4.4.0 (2024-04-24)
Platform: aarch64-apple-darwin20
Running under: macOS Sonoma 14.5

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRblas.0.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] spatialLIBD_1.16.2          SpatialExperiment_1.14.0   
 [3] SingleCellExperiment_1.26.0 SummarizedExperiment_1.34.0
 [5] Biobase_2.64.0              GenomicRanges_1.56.1       
 [7] GenomeInfoDb_1.40.1         IRanges_2.38.1             
 [9] S4Vectors_0.42.1            BiocGenerics_0.50.0        
[11] MatrixGenerics_1.16.0       matrixStats_1.4.1          
[13] BiocManager_1.30.25        

loaded via a namespace (and not attached):
  [1] RColorBrewer_1.1-3        jsonlite_1.8.9           
  [3] magrittr_2.0.3            ggbeeswarm_0.7.2         
  [5] magick_2.8.5              BiocIO_1.14.0            
  [7] fields_16.3               zlibbioc_1.50.0          
  [9] vctrs_0.6.5               memoise_2.0.1            
 [11] config_0.3.2              Rsamtools_2.20.0         
 [13] DelayedMatrixStats_1.26.0 paletteer_1.6.0          
 [15] RCurl_1.98-1.16           benchmarkme_1.0.8        
 [17] htmltools_0.5.8.1         S4Arrays_1.4.1           
 [19] AnnotationHub_3.12.0      curl_5.2.3               
 [21] BiocNeighbors_1.22.0      SparseArray_1.4.8        
 [23] sass_0.4.9                bslib_0.8.0              
 [25] htmlwidgets_1.6.4         plotly_4.10.4            
 [27] cachem_1.1.0              GenomicAlignments_1.40.0 
 [29] mime_0.12                 lifecycle_1.0.4          
 [31] iterators_1.0.14          pkgconfig_2.0.3          
 [33] rsvd_1.0.5                Matrix_1.7-0             
 [35] R6_2.5.1                  fastmap_1.2.0            
 [37] GenomeInfoDbData_1.2.12   shiny_1.9.1              
 [39] digest_0.6.37             colorspace_2.1-1         
 [41] rematch2_2.1.2            AnnotationDbi_1.66.0     
 [43] scater_1.32.1             irlba_2.3.5.1            
 [45] ExperimentHub_2.12.0      RSQLite_2.3.7            
 [47] beachmat_2.20.0           filelock_1.0.3           
 [49] fansi_1.0.6               httr_1.4.7               
 [51] abind_1.4-8               compiler_4.4.0           
 [53] withr_3.0.1               bit64_4.5.2              
 [55] doParallel_1.0.17         attempt_0.3.1            
 [57] BiocParallel_1.38.0       viridis_0.6.5            
 [59] DBI_1.2.3                 maps_3.4.2               
 [61] sessioninfo_1.2.2         rappdirs_0.3.3           
 [63] DelayedArray_0.30.1       rjson_0.2.23             
 [65] tools_4.4.0               vipor_0.4.7              
 [67] beeswarm_0.4.0            httpuv_1.6.15            
 [69] glue_1.8.0                restfulr_0.0.15          
 [71] promises_1.3.0            grid_4.4.0               
 [73] generics_0.1.3            gtable_0.3.5             
 [75] tidyr_1.3.1               data.table_1.16.0        
 [77] ScaledMatrix_1.12.0       BiocSingular_1.20.0      
 [79] utf8_1.2.4                XVector_0.44.0           
 [81] stringr_1.5.1             ggrepel_0.9.6            
 [83] BiocVersion_3.19.1        foreach_1.5.2            
 [85] pillar_1.9.0              spam_2.11-0              
 [87] limma_3.60.6              later_1.3.2              
 [89] benchmarkmeData_1.0.4     dplyr_1.1.4              
 [91] BiocFileCache_2.12.0      lattice_0.22-6           
 [93] rtracklayer_1.64.0        bit_4.5.0                
 [95] tidyselect_1.2.1          locfit_1.5-9.10          
 [97] Biostrings_2.72.1         scuttle_1.14.0           
 [99] gridExtra_2.3             edgeR_4.2.1              
[101] statmod_1.5.0             DT_0.33                  
[103] stringi_1.8.4             UCSC.utils_1.0.0         
[105] lazyeval_0.2.2            yaml_2.3.10              
[107] shinyWidgets_0.8.7        codetools_0.2-20         
[109] tibble_3.2.1              cli_3.6.3                
[111] xtable_1.8-4              jquerylib_0.1.4          
[113] munsell_0.5.1             golem_0.5.1              
[115] Rcpp_1.0.13               dbplyr_2.5.0             
[117] png_0.1-8                 XML_3.99-0.17            
[119] parallel_4.4.0            ggplot2_3.5.1            
[121] blob_1.2.4                dotCall64_1.2            
[123] sparseMatrixStats_1.16.0  bitops_1.0-9             
[125] viridisLite_0.4.2         scales_1.3.0             
[127] purrr_1.0.2               crayon_1.5.3             
[129] rlang_1.1.4               cowplot_1.1.3            
[131] KEGGREST_1.44.1          
```

</details>

Indicate whether `BiocManager::valid()` returns `TRUE`. 

- [x] `BiocManager::valid()` is `TRUE`

**Note**. To avoid potential issues with version mixing and reproducibility, do
not install packages from `GitHub`.

**Comment by lcolladotor** [comment] 2024-10-15 19:00
Hi,

This is mostly likely a duplicate of https://github.com/LieberInstitute/spatialLIBD/issues/84#issuecomment-2319113667 and https://github.com/LieberInstitute/spatialLIBD/issues/85.

Best,
Leo

**Closed as completed** 2024-10-22 12:45 UTC
Labels: duplicate
